# Generated by Django 2.2 on 2020-03-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200313_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='fromais',
            field=models.CharField(default='', max_length=256, verbose_name='数据采集船舶AIS信息'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='toais',
            field=models.CharField(default='', max_length=256, verbose_name='目标船舶AIS信息'),
        ),
    ]
